"""LangGraph node for generating progressive code-review hints."""

import os
from typing import Any, Dict, List

import structlog
from langchain_core.runnables.config import RunnableConfig
from langchain_openai import ChatOpenAI
from pydantic import SecretStr
from tenacity import retry, stop_after_attempt, wait_exponential

from app.core.config import settings
from app.core.observability import langfuse_callback_handler
from app.prompts.hints import HINT_SYSTEM_PROMPT
from app.schemas.review import Finding, HintLevel, HintState, MentorResponse

logger: Any = structlog.get_logger(__name__)


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    reraise=True,
)
async def invoke_structured_llm_with_retry(system_prompt: str, user_payload: str) -> MentorResponse:
    """Invoke the mentor model and return a schema-validated hint response.

    Args:
        system_prompt: The instructions that define the mentoring behaviour.
        user_payload: The code-review context supplied to the model.

    Returns:
        The validated structured hint generated by the model.
    """
    api_key: SecretStr = SecretStr(os.environ.get("LITELLM_API_KEY", ""))
    base_url: str = os.environ.get("LITELLM_BASE_URL", "https://management.sprints.ai/litellm")
    llm: ChatOpenAI = ChatOpenAI(
        model=settings.HINT_LLM_MODEL,
        api_key=api_key,
        base_url=base_url,
        max_retries=0,
    )
    structured_llm: Any = llm.with_structured_output(MentorResponse)
    invocation_config: RunnableConfig = {}
    if settings.LANGFUSE_TRACING_ENABLED:
        invocation_config["callbacks"] = [langfuse_callback_handler]

    logger.info("hint_llm_invocation_started", payload_length=len(user_payload))
    response: Any = await structured_llm.ainvoke(
        [("system", system_prompt), ("human", user_payload)],
        config=invocation_config,
    )
    mentor_response: MentorResponse = (
        response if isinstance(response, MentorResponse) else MentorResponse.model_validate(response)
    )
    return mentor_response


async def generate_hint_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a hint, record its level, and escalate the following hint level.

    Args:
        state: LangGraph state containing hint state, code, findings, and query.

    Returns:
        A dictionary containing the latest hint and updated hint state only.
    """
    raw_problem_id: Any = state.get("problem_id")
    incoming_problem_id: str | None = raw_problem_id if isinstance(raw_problem_id, str) else None
    raw_hint_state: Any = state.get("hint_state")
    try:
        hint_state: HintState = HintState.model_validate(raw_hint_state) if raw_hint_state is not None else HintState()
    except (TypeError, ValueError):
        logger.warning("invalid_hint_state_using_default")
        hint_state = HintState()

    if incoming_problem_id != hint_state.current_problem_id:
        hint_state = hint_state.model_copy(
            update={
                "current_problem_id": incoming_problem_id,
                "current_level": HintLevel.NUDGE,
                "history": [],
            }
        )
    else:
        hint_state = hint_state.model_copy(update={"current_problem_id": incoming_problem_id})

    raw_code: Any = state.get("code", "")
    raw_user_query: Any = state.get("user_query", "")
    raw_findings: Any = state.get("findings", [])
    code: str = raw_code if isinstance(raw_code, str) else ""
    user_query: str = raw_user_query if isinstance(raw_user_query, str) else ""
    findings: List[Finding] = []
    if isinstance(raw_findings, list):
        for finding_index, raw_finding in enumerate(raw_findings):
            try:
                findings.append(Finding.model_validate(raw_finding))
            except (TypeError, ValueError):
                logger.warning("invalid_finding_skipped", finding_index=finding_index)

    serialized_findings: List[Dict[str, Any]] = [finding.model_dump() for finding in findings]
    current_level: HintLevel = hint_state.current_level
    user_payload: str = (
        f"Current hint level: {current_level.value}\n\n"
        f"Developer code:\n{code}\n\n"
        f"Review findings:\n{serialized_findings}\n\n"
        f"User query:\n{user_query}"
    )

    logger.info(
        "hint_generation_started",
        current_level=current_level.value,
        finding_count=len(findings),
        code_length=len(code),
    )
    try:
        latest_hint: MentorResponse = await invoke_structured_llm_with_retry(HINT_SYSTEM_PROMPT, user_payload)
    except Exception:
        logger.exception(
            "hint_generation_failed_using_fallback",
            current_level=current_level.value,
            finding_count=len(findings),
        )
        latest_hint = MentorResponse(
            understanding="I am currently experiencing a system disruption and cannot fully analyze your intent.",
            explanation="The mentoring system is temporarily unavailable or timing out.",
            hint="Review the code connected to the reported findings and identify where its behaviour differs from your intent.",
            next_step="Which assumption in this code path could you test first to narrow down the issue?",
        )

    next_level: HintLevel = HintLevel.CONCRETE_STEP
    if current_level == HintLevel.NUDGE:
        next_level = HintLevel.DIRECTION
    elif current_level == HintLevel.DIRECTION:
        next_level = HintLevel.CONCRETE_STEP

    updated_history: List[HintLevel] = [*hint_state.history, current_level]
    updated_hint_state: HintState = hint_state.model_copy(
        update={"current_level": next_level, "history": updated_history}
    )
    logger.info(
        "hint_state_escalated",
        delivered_level=current_level.value,
        next_level=next_level.value,
        history_count=len(updated_history),
    )
    return {
        "latest_hint": latest_hint.model_dump(),
        "hint_state": updated_hint_state.model_dump(),
    }
