"""LangGraph node for generating progressive code-review hints (Step 4 in 5-step pipeline)."""

from typing import Any, List

import structlog
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.runnables.config import RunnableConfig
from langchain_openai import ChatOpenAI
from pydantic import SecretStr
from tenacity import retry, stop_after_attempt, wait_exponential

from app.core.config import settings
from app.core.observability import build_langfuse_config
from app.core.prompts import load_hint_system_prompt
from app.schemas import GraphState

logger: Any = structlog.get_logger(__name__)

_hint_llm: ChatOpenAI | None = None


def _get_hint_llm() -> ChatOpenAI:
    """Return the shared hint LLM client, built once per process."""
    global _hint_llm
    if _hint_llm is None:
        _hint_llm = ChatOpenAI(
            model=settings.HINT_LLM_MODEL,
            api_key=SecretStr(settings.LITELLM_API_KEY),
            base_url=settings.LITELLM_BASE_URL,
            max_retries=0,
        )
    return _hint_llm


def _extract_message_content(message: Any) -> str:
    """Extract string content safely from either a BaseMessage object or a message dict."""
    if isinstance(message, BaseMessage):
        return str(message.content)
    if isinstance(message, dict):
        return str(message.get("content", ""))
    return str(message)


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    reraise=True,
)
async def invoke_llm_with_retry(
    system_prompt: str,
    user_query: str,
    config: RunnableConfig | None = None,
) -> str:
    """Invoke the mentor LLM directly and return the raw text response.

    Args:
        system_prompt: The rendered mentor system prompt.
        user_query: The latest user query.
        config: Optional runnable config; langfuse tracing callbacks are merged in.

    Returns:
        The raw text draft generated by the LLM.
    """
    llm = _get_hint_llm()

    logger.info("hint_llm_invocation_started", query_length=len(user_query))
    response = await llm.ainvoke(
        [("system", system_prompt), ("human", user_query)],
        config=build_langfuse_config(config),
    )

    if isinstance(response, AIMessage):
        return str(response.content)
    return str(response)


async def generate_hint_node(state: GraphState, config: RunnableConfig | None = None) -> dict[str, Any]:
    """Generate a mentor hint draft and populate GraphState.draft_response.

    Args:
        state: The current GraphState (Pydantic instance — attribute access only).
        config: Optional runnable config used for langfuse tracing.

    Returns:
        A partial state update containing the ``draft_response``.
    """
    # 1. Inbound Guardrail Check (Step 1 short-circuit)
    if not getattr(state, "is_safe_intent", True):
        logger.warning("generate_hint_node_bypassed_due_to_inbound_violation")
        redirect_message = (
            getattr(state, "constructive_redirect", None)
            or "I cannot fulfill this request due to input policy boundaries."
        )
        return {"draft_response": redirect_message}

    # 2. Extract context variables from GraphState and Config metadata
    metadata = (config or {}).get("metadata", {})
    username: str = metadata.get("username", "Developer")

    messages: List[Any] = getattr(state, "messages", [])
    user_query = _extract_message_content(messages[-1]) if messages else ""

    code_context = getattr(state, "code_context", "")  # Retrieved from pgvector in Step 3
    long_term_memory = getattr(state, "long_term_memory", "")
    skill_profile = getattr(state, "skill_profile", "")
    summary = getattr(state, "summary", "")
    outbound_trigger_reason = getattr(state, "outbound_trigger_reason", None)

    # 3. Render System Prompt from cached hints.md template
    system_prompt = load_hint_system_prompt(
        username=username,
        long_term_memory=long_term_memory,
        skill_profile=skill_profile,
        summary=summary,
        code_context=code_context,
        outbound_trigger_reason=outbound_trigger_reason,
    )

    logger.info("generating_hint_draft", user_query_len=len(user_query), code_len=len(code_context))

    # 4. Invoke LLM to produce draft hint text directly
    try:
        draft_text = await invoke_llm_with_retry(system_prompt, user_query, config)
    except Exception:
        logger.exception("hint_generation_failed_using_fallback")
        draft_text = (
            "I am currently experiencing a system disruption and cannot fully analyze your code.\n\n"
            "Review the code connected to your recent changes and identify where its behavior differs from your intent."
        )

    # 5. Save output into GraphState.draft_response for Step 5 (Outbound Guardrail)
    return {"draft_response": draft_text}
